"""Public package for Analog Validation Studio.

The package is controller-neutral: importing it must not require a serial
driver, GUI toolkit, board SDK, or physical hardware.
"""

from .adapters import AdapterState, DeviceAdapter
from .config import (
    MAX_CONFIG_BYTES,
    VALIDATION_CONFIG_SCHEMA_VERSION,
    ChannelConfig,
    ChannelRole,
    ProfileConfig,
    TimeoutConfig,
    ValidationConfig,
    dump_validation_config_json,
    load_validation_config,
    parse_validation_config_json,
    validate_config_capabilities,
    validation_config_to_dict,
)
from .domain import (
    CAPABILITY_SCHEMA_VERSION,
    MEASUREMENT_SCHEMA_VERSION,
    TEST_RUN_SCHEMA_VERSION,
    ChannelRange,
    DeviceCapabilities,
    DeviceCommand,
    EvidenceSource,
    Measurement,
    MeasurementStatus,
    MeasurementUnit,
    QualityFlag,
    SafeRange,
    TestRunMetadata,
    TestRunOutcome,
    TestRunResult,
)
from .errors import (
    AdapterConnectionError,
    AdapterDataError,
    AdapterError,
    AdapterStateError,
    AnalogValidationError,
    CapabilityError,
    ConfigurationError,
    CrcMismatch,
    FrameTooLong,
    FramingError,
    ProtocolError,
    UnsupportedProtocolVersion,
    ValidationError,
)
from .protocol import (
    CRC16_CCITT_FALSE_INITIAL,
    CRC16_CCITT_FALSE_POLYNOMIAL,
    CRC16_CCITT_FALSE_XOR_OUT,
    MAX_RECORD_BYTES,
    Frame,
    crc16_ccitt_false,
    decode_frame,
    encode_frame,
)
from .version import __version__

__all__ = [
    "CAPABILITY_SCHEMA_VERSION",
    "CRC16_CCITT_FALSE_INITIAL",
    "CRC16_CCITT_FALSE_POLYNOMIAL",
    "CRC16_CCITT_FALSE_XOR_OUT",
    "MAX_CONFIG_BYTES",
    "MAX_RECORD_BYTES",
    "MEASUREMENT_SCHEMA_VERSION",
    "TEST_RUN_SCHEMA_VERSION",
    "VALIDATION_CONFIG_SCHEMA_VERSION",
    "AdapterConnectionError",
    "AdapterDataError",
    "AdapterError",
    "AdapterState",
    "AdapterStateError",
    "AnalogValidationError",
    "CapabilityError",
    "ChannelConfig",
    "ChannelRange",
    "ChannelRole",
    "ConfigurationError",
    "CrcMismatch",
    "DeviceAdapter",
    "DeviceCapabilities",
    "DeviceCommand",
    "EvidenceSource",
    "Frame",
    "FrameTooLong",
    "FramingError",
    "Measurement",
    "MeasurementStatus",
    "MeasurementUnit",
    "ProfileConfig",
    "ProtocolError",
    "QualityFlag",
    "SafeRange",
    "TestRunMetadata",
    "TestRunOutcome",
    "TestRunResult",
    "TimeoutConfig",
    "UnsupportedProtocolVersion",
    "ValidationConfig",
    "ValidationError",
    "__version__",
    "crc16_ccitt_false",
    "decode_frame",
    "dump_validation_config_json",
    "encode_frame",
    "load_validation_config",
    "parse_validation_config_json",
    "validate_config_capabilities",
    "validation_config_to_dict",
]
