"""Public bounded ASCII framing and CRC primitives."""

from .afe_v1 import (
    AFE_NAMESPACE,
    AFE_PROFILE_NAME,
    AFE_PROFILE_VERSION,
    AfeCapabilityChannel,
    AfeCapabilityDevice,
    AfeCapabilityEnd,
    AfeCapabilityMessage,
    AfeCapabilityRequest,
    AfeCommand,
    AfeCommandKind,
    AfeMessage,
    AfeTelemetry,
    CapabilityChannelKind,
    capabilities_to_messages,
    capability_messages_to_domain,
    commands_from_mask,
    commands_to_mask,
    encode_afe_message,
    parse_afe_message,
    telemetry_to_measurements,
    validate_command_capability,
)
from .crc import (
    CRC16_CCITT_FALSE_INITIAL,
    CRC16_CCITT_FALSE_POLYNOMIAL,
    CRC16_CCITT_FALSE_XOR_OUT,
    crc16_ccitt_false,
)
from .framing import MAX_RECORD_BYTES, Frame, decode_frame, encode_frame

__all__ = [
    "AFE_NAMESPACE",
    "AFE_PROFILE_NAME",
    "AFE_PROFILE_VERSION",
    "CRC16_CCITT_FALSE_INITIAL",
    "CRC16_CCITT_FALSE_POLYNOMIAL",
    "CRC16_CCITT_FALSE_XOR_OUT",
    "MAX_RECORD_BYTES",
    "AfeCapabilityChannel",
    "AfeCapabilityDevice",
    "AfeCapabilityEnd",
    "AfeCapabilityMessage",
    "AfeCapabilityRequest",
    "AfeCommand",
    "AfeCommandKind",
    "AfeMessage",
    "AfeTelemetry",
    "CapabilityChannelKind",
    "Frame",
    "capabilities_to_messages",
    "capability_messages_to_domain",
    "commands_from_mask",
    "commands_to_mask",
    "crc16_ccitt_false",
    "decode_frame",
    "encode_afe_message",
    "encode_frame",
    "parse_afe_message",
    "telemetry_to_measurements",
    "validate_command_capability",
]
